scanner:
    diff_only: True
    linter: pycodestyle

pycodestyle:
    ignore:
        - E121 # Continuation line under-indented for hanging indent
        - E123 # Closing bracket does not match indentation of opening bracket's line
        - E126 # Continuation line over-indented for hanging indent
        - E133 # Closing bracket is missing indentation
        - E203 # Whitespace before ':'
        - E226 # Missing whitespace around arithmetic operator
        - E241 # Multiple spaces after ','
        - E242 # Tab after ','
        - E501 # Line too long
        - E704 # Multiple statements on one line
        - W503 # Line break occurred before a binary operator
        - W504 # Line break occurred after a binary operator
        - W505 #
        - W605 # Invalid escape sequence 'x'

no_blank_comment: True # If True, no comment is made on PR without any errors.
