import click

from clinica.pipelines.cli import cli as run_cli


@click.command(
    "deeplearning-prepare-data",
    deprecated=True,
    context_settings={
        "allow_extra_args": True,
        "ignore_unknown_options": True,
    },
)
def cli(*args, **kwargs):
    """Prepare data generated by Clinica for PyTorch with tensor extraction."""
    click.echo(
        "Functionalities provided by this pipeline have been moved to the `clinicadl` package."
        "\n\n"
        "See: https://clinicadl.readthedocs.io/en/stable/Preprocessing/Extract/"
    )


run_cli.add_command(cli)
