import nipype.interfaces.io as nio
import pydra
from pydra.tasks.nipype1.utils import Nipype1Task


@pydra.mark.task
@pydra.mark.annotate({"return": {"output_file": str}})
def bids_writer(output_file):
    """
    (Dummy) Task to echo files generated by the core workflow
    """

    print("printing core vars in output_workflow", output_file)

    return "dummy_output_string"