pipeline {
  options {
    timeout(time: 2, unit: 'HOURS')
    disableConcurrentBuilds(abortPrevious: true)
  }
  agent none
  stages {
    stage('Checkout') {
      failFast true
      parallel {
        stage('Test on Linux') {
          agent {
            label 'ubuntu'
          }
          environment {
            CONDA_ENV = "$WORKSPACE/env"
            CONDA_HOME = "$HOME/miniconda"
            PATH = "$HOME/.local/bin:$PATH"
            POETRY = "poetry"
          }
          stages {
            stage('Build environment') {
              steps {
                sh 'echo "Agent name is ${NODE_NAME}"'
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  make env.conda
                  conda activate "${CONDA_ENV}"
                  conda info
                  if ! command -v $POETRY &> /dev/null
                  then
                    echo "$POETRY could not be found"
                    exit
                  else
                    echo "$($POETRY --version) installed at : $(which $POETRY)"
                  fi
                '''
              }
            }
            stage('Install Clinica') {
              steps {
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  conda activate "${CONDA_ENV}"
                  make install
                  clinica --help
                  conda list
                '''
              }
            }
            stage('Test instantiation') {
              environment {
                PATH = "/usr/local/Modules/bin:$PATH"
                WORK_DIR = '/mnt/data/ci/working_dir_linux'
                INPUT_DATA_DIR = '/mnt/data_ci'
              }
              steps {
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  conda activate "${CONDA_ENV}"
                  source /usr/local/Modules/init/profile.sh
                  module load clinica.all
                  cd test
                  taskset -c 0-21 poetry run pytest \
                    --junitxml=./test-reports/instantiation_linux.xml \
                    --verbose \
                    --working_directory=$WORK_DIR \
                    --input_data_directory=$INPUT_DATA_DIR \
                    --disable-warnings \
                    --timeout=0 \
                    -n 4 \
                    ./instantiation/
                '''
              }
              post {
                always {
                  junit 'test/test-reports/*.xml'
                }
                success {
                  sh 'rm -rf ${WORK_DIR}/*'
                }
              }
            }
            stage('Test converters') {
              environment {
                PATH = "/usr/local/Modules/bin:$PATH"
                WORK_DIR = '/mnt/data/ci/working_dir_linux'
                INPUT_DATA_DIR = '/mnt/data_ci'
                TMP_BASE = '/mnt/data/ci/tmp'
              }
              steps {
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  conda activate "${CONDA_ENV}"
                  source /usr/local/Modules/init/profile.sh
                  module load clinica.all
                  cd test
                  taskset -c 0-21 poetry run pytest \
                    --junitxml=./test-reports/run_converters_linux.xml \
                    --verbose \
                    --working_directory=$WORK_DIR \
                    --input_data_directory=$INPUT_DATA_DIR \
                    --basetemp=$TMP_BASE \
                    --disable-warnings \
                    --timeout=0 \
                    -n 2 \
                    ./nonregression/iotools/test_run_converters.py
                  '''
              }
              post {
                always {
                  junit 'test/test-reports/*.xml'
                }
                success {
                  sh '''
                    rm -rf ${WORK_DIR}/*
                    rm -rf ${TMP_BASE}/*
                  '''
                }
              }
            }
	    stage('Non Regression Fast') {
              environment {
                PATH = "/usr/local/Modules/bin:$PATH"
                WORK_DIR = "/mnt/data/ci/working_dir_linux"
                INPUT_DATA_DIR = "/mnt/data_ci"
                TMP_DIR = "/mnt/data/ci/tmp"
                }
              steps {
                catchError(buildResult: 'FAILURE', stageResult: 'UNSTABLE'){
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  conda activate $CONDA_ENV
                  mkdir -p $WORK_DIR
                  source /usr/local/Modules/init/profile.sh
                  module load clinica.all
                  cd test
                  poetry run pytest \
                    --junitxml=./test-reports/nonregression_linux.xml \
                    --verbose \
                    --working_directory=$WORK_DIR \
                    --input_data_directory=$INPUT_DATA_DIR \
                    --basetemp=$TMP_DIR \
                    --disable-warnings \
                    --timeout=0 \
                    -n 4 \
                    -m "fast" \
                    ./nonregression
                '''
                }
              }
	     post {
                always {
                  junit 'test/test-reports/*.xml'
                }
                success {
                  sh 'rm -rf ${WORK_DIR}'
                }
              }
            }
            stage('Test iotools') {
              environment {
                PATH = "/usr/local/Modules/bin:$PATH"
                WORK_DIR = '/mnt/data/ci/working_dir_linux'
                INPUT_DATA_DIR = '/mnt/data_ci'
                TMP_BASE = '/mnt/data/ci/tmp'
              }
              steps {
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  conda activate "${CONDA_ENV}"
                  source /usr/local/Modules/init/profile.sh
                  module load clinica.all
                  cd test
                  taskset -c 0-21 poetry run pytest \
                    --junitxml=./test-reports/run_converters_linux.xml \
                    --verbose \
                    --working_directory=$WORK_DIR \
                    --input_data_directory=$INPUT_DATA_DIR \
                    --basetemp=$TMP_BASE \
                    --disable-warnings \
                    --timeout=0 \
                    -n 2 \
                    ./nonregression/iotools/test_run_utils.py
                  '''
              }
              post {
                always {
                  junit 'test/test-reports/*.xml'
                }
                success {
                  sh '''
                    rm -rf ${WORK_DIR}/*
                    rm -rf ${TMP_BASE}/*
                  '''
                }
              }
            }
          }
          post {
            always {
              cleanWs()
            }
          }
        }
        stage('Test on macOS') {
          agent {
            label 'macos'
          }
          environment {
            CONDA_ENV = "$WORKSPACE/env"
            CONDA_HOME = "$HOME/miniconda3"
            PATH = "$HOME/.local/bin:/usr/local/bin:/Users/ci-aramis-clinica/.brew/bin/:$PATH"
          }
          stages {
            stage('Build environment') {
              steps {
                sh 'echo "Agent name is ${NODE_NAME}"'
                sh '''
		  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  make env.conda
                  conda activate "${CONDA_ENV}"
                  conda info
                '''
              }
            }
            stage('Install Clinica') {
              steps {
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  conda activate "${CONDA_ENV}"
                  make install
                  clinica --help
                  conda list
                '''
              }
            }
            stage('Test instantiation') {
              environment {
                WORK_DIR = '/Volumes/data/working_dir_mac'
                INPUT_DATA_DIR = '/Volumes/data_ci'
              }
              steps {
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  conda activate "${CONDA_ENV}"
                  source "$(brew --prefix)/opt/modules/init/bash"
                  module load clinica.all
                  cd test
                  poetry run pytest \
                    --verbose \
                    --working_directory=$WORK_DIR \
                    --input_data_directory=$INPUT_DATA_DIR \
                    --junitxml=./test-reports/instantation_mac.xml \
                    --disable-warnings \
                    ./instantiation/
                '''
              }
              post {
                always {
                  junit 'test/test-reports/*.xml'
                }
                success {
                  sh 'rm -rf ${WORK_DIR}/*'
                }
              }
            }
            stage('Test converters') {
              environment {
                WORK_DIR = '/Volumes/data/working_dir_mac'
                INPUT_DATA_DIR = '/Volumes/data_ci'
                TMP_BASE = '/Volumes/data/tmp'
              }
              steps {
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  conda activate "${CONDA_ENV}"
                  source "$(brew --prefix)/opt/modules/init/bash"
                  module load clinica.all
                  cd test
                  poetry run pytest \
                    --verbose \
                    --working_directory=$WORK_DIR \
                    --input_data_directory=$INPUT_DATA_DIR \
                    --basetemp=$TMP_BASE \
                    --junitxml=./test-reports/run_converters_mac.xml \
                    --disable-warnings \
                    ./nonregression/iotools/test_run_converters.py
                '''
              }
              post {
                always {
                  junit 'test/test-reports/*.xml'
                }
                success {
                  sh '''
                    rm -rf ${WORK_DIR}/*
                    rm -rf ${TMP_BASE}/*
                  '''
                }
              }
            }
            stage('Test iotools') {
              environment {
                WORK_DIR = '/Volumes/data/working_dir_mac'
                INPUT_DATA_DIR = '/Volumes/data_ci'
                TMP_BASE = '/Volumes/data/tmp'
              }
              steps {
                sh '''
                  source "${CONDA_HOME}/etc/profile.d/conda.sh"
                  conda activate "${CONDA_ENV}"
                  source "$(brew --prefix)/opt/modules/init/bash"
                  module load clinica.all
                  cd test
                  poetry run pytest \
                    --verbose \
                    --working_directory=$WORK_DIR \
                    --input_data_directory=$INPUT_DATA_DIR \
                    --basetemp=$TMP_BASE \
                    --junitxml=./test-reports/run_converters_mac.xml \
                    --disable-warnings \
                    ./nonregression/iotools/test_run_utils.py
                '''
              }
              post {
                always {
                  junit 'test/test-reports/*.xml'
                }
                success {
                  sh '''
                    rm -rf ${WORK_DIR}/*
                    rm -rf ${TMP_BASE}/*
                  '''
                }
              }
            }
          }
          post {
            always {
              cleanWs()
            }
          }
        }
      }
    }
  }
  post {
    failure {
      mail to: 'clinica-ci@inria.fr',
        subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
        body: "Something is wrong with ${env.BUILD_URL}"
    }
  }
}
