name: Build and Deloy Documentation

on:
  push:
    branches: ["dev", "maint-*"]
  pull_request:
    branches: ["dev", "maint-*"]

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-deploy-doc:
    runs-on:
      - self-hosted
      - Linux
      - doc-runner
    steps:
      - uses: actions/checkout@v4
      - name: Build documentation
        run: |
          make env.conda
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate "${{ github.workspace }}"/env
          make doc
      - name: Deploy documentation
        run: |
          if [[ -z "${{ github.event.number }}" ]];
          then
            BRANCH_NAME="${{ github.ref_name }}"
          else
            BRANCH_NAME="PR-${{ github.event.number }}"
          fi
          echo $BRANCH_NAME
          mv site "${BRANCH_NAME}"
          ls "${BRANCH_NAME}"
          scp -r "${BRANCH_NAME}" aramislab:/srv/local/clinica/docs/public/

