
on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:

  clean_closed_PR:
    name: Clean_Closed_PR
    runs-on: ubuntu-latest  
    if: github.event.pull_request.merged == true
    steps: 
    - name: curl
      uses: wei/curl@v1
      with:
        args: -v -X POST --user mauricio.diaz-melo@inria.fr:${{ secrets.JENKINS_CLINICA }} https://ci.inria.fr/clinica-aramis/job/clean_env/build
