name: DWI Preprocessing Using Phase Diff Pipelines Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  POETRY_VERSION: '1.6.1'
  PYTHON_VERSION: '3.10'

jobs:
  test-pipelines-dwi-preprocessing-using-phase-diff-MacOS:
    runs-on:
      - self-hosted
      - macOS
      - aramis
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
      - name: Run tests for dwi preprocessing using phase diff pipeline
        run: ./scripts/run_nonregression.sh
        env:
          TEST: dwi/preprocessing/using_phase_diff
          MODALITY: dwi_preprocessing_using_phase_diff
          WORKSPACE: ${{ github.workspace }}

  test-pipelines-dwi-preprocessing-using-phase-diff-Linux:
    runs-on:
      - self-hosted
      - Linux
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: false
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Run tests for dwi preprocessing using phase diff pipeline
        run: ./scripts/run_nonregression.sh
        env:
          TEST: dwi/preprocessing/using_phase_diff
          MODALITY: dwi_preprocessing_using_phase_diff
          WORKSPACE: ${{ github.workspace }}
