from __future__ import print_function
import argcomplete
from argparse import ArgumentParser
from clinica.engine.cworkflow import *
import sys
import os
import subprocess
from clinica.engine.cmdparser import *

def visualize(clinicaWorkflow, ids, rebase=False):
    if not clinicaWorkflow.data.has_key('visualize'):
        print("No visualization was defined")
        exit(0)

    class chdir:
        def __init__(self, base):
            self.pwd = os.getcwd()
            os.chdir(base)
        def __del__(self):
            os.chdir(self.pwd)

    change_directory = None
    if rebase is False:
        change_directory = chdir(clinicaWorkflow.base_dir)
    else:
        change_directory = chdir(rebase)

    print(clinicaWorkflow.data['visualize'])
    program, arguments, matches = clinicaWorkflow.data['visualize']

    def run_program(id): subprocess.Popen([program] + arguments.replace("${%s}" % matches, id).strip().split(" "))
    [run_program(id) for id in ids]

def shell(clinicaWorkflow):
    workflow = clinicaWorkflow
    __banner__ = "workflow variable is instantiated for you!"
    namespace = globals().copy()
    namespace.update(locals())

    def load_python_shell():
        import readline
        import code
        shell = code.InteractiveConsole(namespace)
        shell.interact(banner=__banner__)

    def load_ipython_shell():
        from IPython.terminal.embed import InteractiveShellEmbed
        InteractiveShellEmbed(user_ns=namespace,banner1=__banner__)()

    try:
        load_ipython_shell()
    except:
        try:
            load_python_shell()
        except:
            print("Impossible to load ipython or python shell")

def load_conf(args):
    import cPickle

    def load(path):
        file = os.path.join(path, "clinica.pkl")
        if os.path.isfile(file): return cPickle.load(open(file))
        return False

    wk = False

    if len(args) == 0:
        wk = load(os.getcwd())
    elif os.path.isdir(args[0]):
        wk = load(args[0])

    if not wk:
        print("No <clinica.pkl> file found!")
        exit(0)

    return wk

def execute():
    """
    clinica <command> [path=current_directory] [options]
    ex:
    $cd WorkingDir/
    $clinica visualize --id=1,2,3
    """
    parser = ArgumentParser()
    sub_parser = parser.add_subparsers()
    parser.add_argument("-q", "--quiet",
                      action="store_false", dest="verbose", default=True,
                      help="don't print status messages to stdout")

    """
    visualize option: open image[s] in a specific GUI program, generated by a pipeline
    """
    vis_parser = sub_parser.add_parser('visualize')
    vis_parser.add_argument("-i", "--id", dest="id",
                      required=True,
                      help="unique identifier")
    vis_parser.add_argument("-r", "--rebase", dest="rebase",
                      default=False,
                      help="unique identifier")
    def vis_parser_fun(args):
        visualize(load_conf(args[1:]), args.id.split(","), args.rebase)
    vis_parser.set_defaults(func=vis_parser_fun)

    """
    shell option: re-open a nipype.Workflow object within python/ipython session
    """
    shell_parser = sub_parser.add_parser('shell')
    def shell_parser_fun(args):
        shell(load_conf(args[1:]))
    shell_parser.set_defaults(func=shell_parser_fun)

    """
    run option: run one of the available pipelines
    """
    run_parser = sub_parser.add_parser('run')
    run_parser.add_argument("-l", dest="list",
                            action="store_true", default=False,
                            help="show all available pipelines")
    #adding the independent pipeline ArgumentParser objects
    init_cmdparser_objects(run_parser.add_subparsers())

    try:
        argcomplete.autocomplete(parser)
        args = parser.parse_args("run T1 -s hey".split(" "))
    except:
        sys.stdout.flush()
        parser.print_help()
        exit(0)

    if args.list is True:
        print(*get_cmdparser_names())
    else:
        args.func(args)

if __name__ == '__main__':
    execute()
